* Day 5: Avventura idrotermale
  Ti imbatti in un campo di *sorgenti idrotermali* sul fondo dell'oceano!
  Queste sorgenti producono costantemente nuvole grandi e opache, quindi sarebbe meglio evitarle se possibile.\\

  Tendono a formarsi in linee: il sottomarino produce un elenco di linee generati dai flussi emanati dalle sorgenti vicine (il tuo input di puzzle).
  Per esempio:
  
  |------------|
  | 0,9 -> 5,9 |
  | 8,0 -> 0,8 |
  | 9,4 -> 3,4 |
  | 2,2 -> 2,1 |
  | 7,0 -> 7,4 |
  | 6,4 -> 2,0 |
  | 0,9 -> 2,9 |
  | 3,4 -> 1,4 |
  | 0,0 -> 8,8 |
  | 5,5 -> 8,2 |
  |------------|

  Ogni flusso termale è espresso come un segmento di linea nel formato =x1,y1 -> x2,y2= dove =x1,y1= sono le coordinate di un'estremità del segmento di linea e =x2,y2= sono le coordinate dell'altra estremità.
  Questi segmenti di linea includono i punti ad entrambe le estremità.
  In altre parole:
  - Una riga con =1,1 -> 1,3= copre i punti =1,1=, =1,2= e =1,3=.
  - Una riga con =9,7 -> 7,7= copre i punti =9,7=, =8,7= e =7,7=.

  Per ora, *considera solo le linee orizzontali e verticali*: linee dove =x1 = x2= o =y1 = y2=.\\
  
  Quindi, le linee orizzontali e verticali dell'elenco sopra produrrebbero il seguente diagramma:
  #+begin_src
  .......1..
  ..1....1..
  ..1....1..
  .......1..
  .112111211
  ..........
  ..........
  ..........
  ..........
  222111....
  #+end_src
  
  In questo diagramma, l'angolo in alto a sinistra è =0,0= e l'angolo in basso a destra è =9,9=.
  In ogni posizione è mostrata il numero di linee che coprono quel punto, oppure =.= se nessuna linea copre quel punto.
  La coppia di =1= in alto a sinistra, ad esempio, proviene dal dato =2,2 -> 2,1=.
  La riga più in basso è formata dalle linee =0,9 -> 5,9= e =0,9 -> 2,9= che si sovrappongono.\\

  Per evitare le zone più pericolose, è necessario determinare il numero di punti in cui si sovrappongono almeno due linee.
  Nell'esempio sopra, questo accade quando occore il valore =2= o di più, per un totale di =5= punti complessivi.\\

  Considerando solo le linee orizzontali e verticali:
  *in quanti punti si sovrappongono almeno due linee?*

** Part 2
   Sfortunatamente, considerare solo le linee orizzontali e verticali non ti dà il quadro completo: è necessario considerare anche le linee diagonali.\\

   A causa dei limiti del sistema di mappatura delle sorgenti idrotermali, le linee nell'elenco saranno sempre e solo =orizzontali=, =verticali= o =diagonali a esattamente 45 gradi=.
   In altre parole:

   - Una voce come =1,1 -> 3,3= copre i punti =1,1=, =2,2= e =3,3=.
   - Una voce come =9,7 -> 7,9= copre i punti =9,7=, =8,8= e =7,9=.

   Considerando tutte le linee dell'esempio precedente, ora produrrebbe il seguente diagramma:
   
   #+begin_src
   1.1....11. 
   .111...2.. 
   ..2.1.111. 
   ...1.2.2.. 
   .112313211 
   ...1.2.... 
   ..1...1... 
   .1.....1.. 
   1.......1. 
   222111.... 
   #+end_src

   Devi ancora determinare il numero di punti in cui almeno due linee si sovrappongono.
   Nell'esempio precedente, il totale è =12=x punti.

   Considerando tutte le linee:
   *in quanti punti si sovrappongono almeno due linee?*
